[package]
name = "map"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.126"
js-sys = "0.3"
itertools = "0.15.0"
log = "0.4.33"
console_log = "1.0.0"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.76"

wgpu = { version = "23.0", features = ["webgl"] }
image = "0.25.10"
bytemuck = { version = "1.25.0", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Element",
  "HtmlCanvasElement",
  "WebGlRenderingContext",
  "Window",
  "console",
  "MouseEvent",
  "KeyboardEvent"
]
